CREATE TABLE PERSON (
  ID INTEGER NOT NULL,
  NAME VARCHAR(255) NOT NULL,
  LOCATION VARCHAR(255),
  BIRTH_DATE TIMESTAMP,
  PRIMARY KEY (ID)
);

INSERT INTO PERSON (ID, NAME, LOCATION, BIRTH_DATE) VALUES (10001, 'OSKI', 'WARSAW', SYSDATE);
INSERT INTO PERSON (ID, NAME, LOCATION, BIRTH_DATE) VALUES (10002, 'ARAP', 'CHICAGO', SYSDATE);
INSERT INTO PERSON (ID, NAME, LOCATION, BIRTH_DATE) VALUES (10003, 'DOLAN', 'PLOCK', SYSDATE);